### ISSUE TITLE
In BIZ UDPGothic Regular, U+2264 (≤) and U+2265 (≥) are assigned in reverse

### ISSUE THREAD

**Issue by ln-north** [googlefonts/morisawa-biz-ud-gothic#21]
It appears that in BIZ UDPGothic Regular, U+2264 (≤) and U+2265 (≥) are assigned in reverse. ([Preview](https://fonts.google.com/specimen/BIZ+UDPGothic?preview.text=%E2%89%A4%E2%89%A6%20%E2%89%A7%E2%89%A5&preview.text_type=custom&query=BIZ))

<img width="1379" alt="スクリーンショット 2023-09-01 7 49 42" src="https://github.com/googlefonts/morisawa-biz-ud-gothic/assets/8067736/53937820-9c63-428c-9a49-5d306a144e44">

Same in glyphs file.

<img width="1917" alt="スクリーンショット 2023-09-01 7 48 45" src="https://github.com/googlefonts/morisawa-biz-ud-gothic/assets/8067736/330c1f7d-d812-430c-9bd4-c92e49cbb5b6">

**Comment by xxdgwxx** [comment]
Hi @aaronbell! Any thoughts? cc @glenda-tn

**Comment by aaronbell** [comment]
Thanks! Resolved this with the latest release. 
https://github.com/googlefonts/morisawa-biz-ud-gothic/releases/tag/v1.051
