### ISSUE TITLE
Incorrect font family name in Japanese

### ISSUE THREAD

**Issue by akihironagai** [googlefonts/morisawa-biz-ud-gothic#4]
Incorrect font family name in Japanese.

It needs to be changed from "BIZ UDPGothic" and "BIZ UDGothic" to "BIZ UDPゴシック" and "BIZ UDゴシック".

This is information of BIZ UDPGothic (incorrect font family name).
![ゴシック](https://user-images.githubusercontent.com/77012577/160230001-24859b5d-040a-4c03-ad22-7ccc57a5e174.png)

This is information of BIZ UDPMincho (incorrect full name).
![明朝](https://user-images.githubusercontent.com/77012577/160230000-5d8dae70-b447-4342-b304-11ac0c202bac.png)

**Comment by aaronbell** [comment]
Thanks. Fixed in the latest PR.
