### ISSUE TITLE
(不具合) U+005Cに円記号が割り当てられている

### ISSUE THREAD

**Issue by libraplanet** [googlefonts/morisawa-biz-ud-gothic#7]
U+005Cに円記号 (¥) が割り当てられており、円記号問題が起こっております。
円記号問題はS-JISなどの日本固有の問題であり、未だに固執しているのは、ほぼWindows系のみです。

「ユニバーサル」を謳うのであれば、日本固有の文字コードではなく、UNICODEの仕様に則って、U+005C には適切にバック スラッシュを割り当てられるフォントであるべきかと思います。特に、Windows以外のデバイスが数多く普及している現代に於いて、U+005C に円記号 (¥) を割り当てる必要性は微塵もなく、円記号問題は不具合と言わざるを得ません。例えば游ゴシックもWindowsにプリインストールされているもののみ意図的に差し替えられており、macOSやパッケージでは U+005C はバック スラッシュです。

また、U+005Cは バック スラッシュ であり、円記号は U+00A5 であると、正しい認識されていく必要があります。

円記号問題の不具合は修正をされることを願います。

**Comment by hiroyuki-komatsu** [comment]
I also prefer to align with Unicode.

I understand the reason and background of why Windows uses yen-mark for U+005C rather than backslash.
On the other hand, this makes other compatibility issues with all other platforms such as Android, ChromeOS, iOS, macOS, etc.

I wondered if it is possible to apply the Unicode standard way for the Google Fonts version at least.
Thank you,

**Comment by davelab6** [comment]
Agreed, we ought to fix this.

**Comment by libraplanet** [comment]
Sorry for my bad English.

I think, it do not need compatibility. because I don't' know why it's necessary yen sign on U+005C as a Japanese. Rather, WEB Fonts should not have that compatibility.

This issue needs to be fixed. With all WEB Fonts, like the wave dash problem.

Thank you.

**Comment by davelab6** [comment]
>  like the wave dash problem

What is that? :)

I agree this needs to be fixed ASAP and have asked in #8 for Unicode compliance to be expedited :)

**Comment by libraplanet** [comment]
Thank you for your understanding.
I am waiting for this problem to be fixed.

The wave dash problem was also a Japanese specific issue that occurred with UNICODE. It has already been fixed. but it took long years to fix it.

For more information, please refer to the following link.

http://std.dkuug.dk/JTC1/SC2/WG2/docs/n4606.pdf

Thank you. :-)

**Comment by hiroyuki-komatsu** [comment]
I'm the author of that proposal for the wave dash issue ;-)

Here's an overview of the two issues. They are similar, but slightly different.

* YEN_SIGN for U+005C: U+005C is the code point for `backslash`, but some fonts show `yen sign` for backward compatibility.
  + Unicode specification should be right, but some implementations do not follow it.
  + UD fonts also show YEN_SIGN for U+005C as we are discussing here.
* Sample glyph of WAVE_DASH: The sample glyph of WAVE_DASH (U+301C) by Unicode was not correct. It was up-side-down of the original standard. Some fonts had followed Unicode, but most fonts show the original one for backward compatibility.
  + Unicode specification was updated.
  + UD fonts do not have this issue.
